# Generated by Django 5.1.1 on 2024-10-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKERS', '0002_alter_worker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
