# Generated by Django 5.1.1 on 2024-10-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WORKERS', '0003_alter_worker_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
