# Generated by Django 5.1.1 on 2024-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKERS', '0004_delete_workerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
